layouts/_default/list.html
The list.html used the paginator with a where clause with section "post".
This panics for sites without secion post, and the plain .Paginator is what you'd really want (will always contain the relevant content
for the given section or taxonomy.
=> Fix list template

layouts/_default/single.html
For some reason the class of an article was set to the name of the Type of the article.
This caused all articles of a different class to have some layout issues (most noticeably: the did not have a margin-left).
=> Fixed #12: css class file names not matching.

README.md, layouts/partials/navigation.html
If you are using an external feed aggregator, you were not able to customize the link, with this commit it is possible to set Params -> RSSLink to a value of choice. It is completely optional, so it would use the normal .../index.xml.
=> Allow to set custom RSS-Link

layouts/partials/header.html
Fetching inconsolata font as well; along with the other google fonts,
this clears up the issue in some devices which don't have a good
monospaced font
Thanks for porting this theme to hugo. Primarily I saw using the theme to render code fell back to sans serif fonts in my mobile device; which kind of looked messy. Let me know if this is okay or if there are alternatives
=> Add inconsolata to the list of google fonts

README.md, data/authors/example.yml, layouts/_default/single.html, layouts/partials/author.html
Cleaned up the code that renders section class="author" in the single layout. Extracted to a
partial, "author.html". Introduced .Params.noauthor to remove the author block entirely.
Introduced a map-based lookup into .Site.Data.authors, based on either a per-page .Params.author
key, or a default .Site.Params.author. Added additional checks to keep new authors partial backwards
compatible with the existing hugo-theme-casper .Site.Params.author/authorlocation/authorwebsite/bio.
=> Adding noauthor and multiple author capability.

README.md, archetypes/default.md, layouts/_default/li.html
Hi @vjeantet 
I added some more support for multiple authors.
1. The "list" page ignores the author specified in a particular post. Now the author's name will appear in any "list" page. I added some additional checking to (hopefully) not break the existing options of author in the main config and no author.
2. Added author to archtypes.
3. Updated readme to better include info on number 2 above.
=> Added some more multi author support.

README.md
```BaseUrl= "http://example.com"``` is confusing.
I think error occurs on this code.
```
<link rel="stylesheet" type="text/css" href="{{.Site.BaseURL}}css/screen.css" />
```
```BaseUrl= "http://example.com/"``` is better.
=> Modify example of BaseUrl

layouts/index.html
- previously only when `Section` was `post`
- now defaults to `post`, but can specify in main config, e.g.
```toml
[params]
paginatedSections = "post article presentation"
```
=> configurable sections for pagination

layouts/_default/single.html, layouts/index.html, layouts/page/cover.html, layouts/page/single.html, layouts/partials/share.html, static/css/screen.css
- In the banner of the cover page, link to social media accounts
- Add instagram, pinterest, and google plus
- In `config.toml`:
```toml
[params]
instagramName = "foobar"
pinterestName = "foobar"
googlePlusName = "foobar"
```
- Each page's social share button also adds Pinterest
- Optionally (but recommended) can set media in front matter of markdown file
```toml
pinterestMedia = "images/foobar.png"
```
=> add instagram, pinterest, and google+

layouts/partials/footer.html, layouts/partials/header.html
- provision to add optional custom header partial, and customer footer partial
- useful for adding own `<script/>` tags (for JS) and `<link/>` tags (for CSS)
```toml
[params]
customFooterPartial = "customFooter.html"
customHeaderPartial = "customHeader.html"
```
=> custom sections in header and footer, via partials

layouts/index.html, static/css/screen.css
Explicitly set text-decoration to none to avoid `a:-webkit-any-link`
applying on social icons. Also add a missing `bloglogo` class back.
Signed-off-by: kfei <kfei@kfei.net>
=> Fix unexpected underline for social icons

layouts/partials/li.html
Fixes #47: Use index correct to find author 
Check whether the `.Params.author` exists in `.Site.Data.authors` before calling `index` on the data object.
=> Fixes #47: Use index correct to find author

layouts/index.html
The previous commit had accidentally copied a 'tag-head' class from list.html to index.html. This caused the index's cover image to be cropped too much.
=> Remove the 'tag-head' class from header.

layouts/index.html, static/css/screen.css
When adding the properties flickrName or email in the [params] section of config.toml the relevant icons will be shown on the cover page.
Example on https://hallgeirholien.no
=> Added icons for flickr and email on cover page

layouts/partials/header.html
This allows Facebook to get the header image properly as well, and uses the correct og:image tag to do so.
=> Added og:image statement

layouts/partials/li.html
Hugo generates summaries for posts which can be used with the .Summary
page variable. The theme uses this to print the summary of each post
in the post list. As it is now, you cannot disable the summary
from being printed, so the partial header li.html is changed
to support the excerpt variable in posts.
When posts do not have an excerpt variable, the behavior is not changed
and the summary is being printed as before. If excerpt exists
and is not empty, then it is printed instead of the summary and if excerpt
is empty, then nothing is printed.
=> Support excerpt variable

layouts/_default/single.html, layouts/partials/suggestions.html
Currently suggestions are only visible for the page section and show content from other sections.
This PR makes them available on other sections.
=> Add suggestions on other sections than « page »

layouts/404.html, layouts/index.html, layouts/partials/social.html
It is likely that users will want to add more social icons so i moved them to a separate partial header to make it easier for someone to change the file. Also, the icons were being used both in index.html and 404.html, so it also avoids code duplication.
However, there was a discrepancy between index and 404. The 404 page had support only for linkedin, github, twitter and not for the ones that were added with pull request #31. Another difference is that index was changed with pull request #35 to use target="_blank".
Were these changes deliberately not made in 404 or it was just missed ? I chose to use the index version of the code because it was more complete.
I also intended to add more icons for bitbucket, gitlab, etc but there are no icons for them in genericons so the code would need …
=> Move social icons into partial header

layouts/partials/li.html
The logic for rendering authors on the front page had issues. The authors set on the post frontmatter were not showing(ignored) as the template logic was trying to override a `$author` variable in a subtle manner.
This fixes the issue and ensures the right author is rendered i.e when the author is set on the frontmatter then he will be picked, and if no author is specified it will default to the site wide author defined in `.Site.Params.author`.
=> Fix multiple author on front page

README.md, layouts/partials/header.html
Add support for syntax highlighting using highlight.js
If the user sets a value to the parameter hjsStyle, the the js script highlight.js will be loaded and colorize code tags using the style selected by the user.
I know that there is support for custom partial headers, so users can individually load highlight.js there, but i think it is a feature many people use, so it is nice to have support for it.
=> Add syntax highlighting for code tags

layouts/partials/header.html
This adds support for extra highlight.js languages by assigning an array to either _config.toml_ or a page/post's front matter:
_config.toml_
```toml
[params]
hjsStyle = "default"
hjsExtraLanguages = ["elm"]
```
_content/post/my-blog-post-about-elm.md_
```
+++
title = "My Blog Post About Elm"
hjsExtraLanguages = ["elm"]
+++
...
```
I've also upgraded highlight.js from v9.6.0 to v9.8.0
=> Add support for extra highlight.js languages

archetypes/default.md
Since Hugo v0.24 I was getting the following warning when creating a new post
```
WARNING: date and/or title missing from archetype file "/Users/evils/Repositories/caffeineflo.github.io/themes/casper/archetypes/default.md". 
From Hugo 0.24 this must be provided in the archetype file itself, if needed. Example:
---
title: "{{ replace .TranslationBaseName "-" " " | title }}"
date: {{ .Date }}
draft: true
---
```
To fix the warning and conform to the latest Hugo changes, I reintroduced the data attribute as per this PR.
=> Added current date to archtype default

layouts/partials/twitter_card.html
Without a configuration setting for 'cover', the `twitter_card.html`
partial fails to render, and throws errors during site build.
Fixes #95
=> Make cover image option in Twitter card

layouts/partials/social.html
I initially considered extending the genericons font with the icon, however no new social icons will be allowed into genericons. (https://github.com/Automattic/Genericons/issues/108)
This proposed change pull an official svg from Stackoverflow.
**To use this:**
If the config.toml contain this:
```
[params]
...
stackoverflowId = "123456"
```
A Stackoverflow logo will appear on the front page with a link to https://stackoverflow.com/users/123456
=> Icon with link to Stackoverflow user page. Solve #99

layouts/partials/twitter_card.html
This fixes a bug introduced in #96.
=> Twitter card should include cover image if present
